#!/bin/bash

# Download the file
wget https://interactivebrokers.github.io/downloads/twsapi_macunix.1035.01.zip
# Unzip the downloaded file
unzip twsapi_macunix.1035.01.zip -d /scripts/
# Enter the directory, change whl filename to match the one generated by the setup.py
chmod -R 777 /scripts/IBJts/source/pythonclient/
cd /scripts/IBJts/source/pythonclient/ && python3 -m pip install .

# Remove the downloaded file
# rm twsapi_macunix.1035.01.zip